Mission joining
Leandro-Barretoo/space-hub pull request #35
Opened 2021-09-07 16:17 UTC by Leandro-Barretoo

In this PR I added the following:
- Added action creator jor joining mission;
- Create an event listener for when a user clicks the button, the reserved: true is added to a specific object.

When you see the project, in the browser open the console and type store.getState() to see the update.

Thank you for the review.

2021-09-07 23:53 UTC, Abdona requested changes
Hallo @Leandro-Barretoo 
you did awesome work so far.

Requested Changes:

- whenever I leave the page and return to it again, or refresh it, the button reserved button is not shown correctly, you are showing the "Join Mission " button always.
- Please fix this problem.

2021-09-07 23:53 UTC, Abdona commented on src/components/MissionCard.js
> +      </td>
Join Mission Rendering on default On Mission Component re rendering.

2021-09-08 07:20 UTC, Leandro-Barretoo commented on src/components/MissionCard.js
> +      </td>
Hello Abdul, just a reminder that the Redux store does not persist the data when reloaded. When you refresh the page, the Redux store resets cause we not using localStorage and not posting anything to API.
It's a good point tho but it's not required, thank you.

2021-09-08 10:52 UTC, Abdona approved these changes
Nothing is Required.
You are done with This PR.
Congratulations.
You can merge now.

2021-09-08 11:11 UTC, merged